travis:
  secure:
    BINSTAR_TOKEN: kHwo/USt5ByK+EIewABFIV55gluWHUM5wm5890P7mbd0adfLKv9d8ST2M4TgyZ1pXz9wlfVQcI227L9iHqte8/abIZ7l85RPaAHYKEVR0NmTc+pbTCW6b9iZrCk/qIEkPcTi3FG+alp12yx3u4Z1IqEzzhqf79CneShNkG4o+Kq96+VNkY5hao6oNRQbXmEHh5RLcq46WEK3+hKaqxfZAWG4ZrpKSYXGbc0abU6vEVWRwglUxeko3DFqqWsPHS0b3YBWVGZI4QYQ1k8Ig2hEz4izJAMOVVf14onkePR2DSp/5DHOAD/m4u2zYpWvIANzi6ulP4vxnuKDsrj02X2meC40xpCOGqUUeEY4vtbMsusEYKBSAUAMwxlVW1c1PIAu90gM9cpQwhJ5/huic4DFfnIMbrQbagWzZdMHuFO8I3oqzTkAc9/0KZRnP4lZWTxvQA2TvPjYRzBllr0N2dGUn6UqHr14SHZRLltV3pnFJs5xgbntxpWhxKmAp0GZQWJ3Ol/2yh6KaQZ0yxyYKSgog5B8+bxzZCdX3wsy4aJI1MUKFSvMNxrNiOTw4+LAK8JwevQJctRVIWcrnTRqayvrTaYvp3AUjr4GHC5nQIaVDZXzPpkM4d3yAHp2KPsbOSRxpIG+ZRQbFiocTll7CPteLUkU0uu5o54nF8NGRT3PqMs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
