travis:
  secure:
    BINSTAR_TOKEN: mt0Xx/fQptb4EMEu9GUIgiHN/XwkKwgPXIsIune4BeO2de2WI12dxonV3OWq5VoLphZ76d7tZ5jf0fbtZZ3ijn9Tu/ddkln6U9PDNMe+eELAyH4eNm+vRf/vhLMzUvFyXHSjN7mtss/zssD1K14uG/KI5J1zTkFqTSTZO5idciQJB/CmahV9cWAZGCU18Asf5P2HcP/sSnbuITCswzu/05jVMctHYYBpB4sWLqxgUQWKaTxaoMljvfVhNFlLGtKajNBvxDU41AK/W21S6ZerQjV2+qJjgGFuwpTUw8Ke0Tk1GbRYvGRWK3vUZkz51hwwLdWSKt4gW2uL5YqWdvCMtuaM5d96+78atXtmIVI43Pxzfqw+++MfNIcbSZqrKBX8t78zk6T30LQ4EpmBfJDWqCCBa9x+PY+VyaYNgyYI+QygAib0kagmpc0FvAt4U2d7GRjsPv3c3wmBvIG0ciJied4kPfYjlPssRcOYhClY+O+TrJ5l0glgBhushYSmxn3b6eKLQeCuV0kWojukjCw2ScIc98VGIIn22uUt3jW2deZZY4uHkhJMDFUd4XqNseE153BUwFCfmU3AL/J1YkD3HjaHBq4RkTKCbQJmuOMcq9SIi34I7LHHWR2vh1J+LpGjL3YYyna0pcnCcN8qEHbksSjOaL+FmwXWD8l2BRU1Q70=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
